apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtractapp
  labels:
    app: subtract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtract
  template:
    metadata:
      labels:
        app: subtract
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subtractapp"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
        dapr.io/log-as-json: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"
        prometheus.io/scheme: "http"

    spec:
      containers:
      - name: subtract
        #image: dapriosamples/distributed-calculator-csharp:latest
        image: "{{ .Values.acr.name }}.azurecr.io/dapriosamples/distributed-calculator-csharp:{{ .Values.subtract.image_tag }}"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value: {{ .Values.appinsights.instrumentationKey | quote }}
