apiVersion: apps/v1
kind: Deployment
metadata:
  name: divideapp
  labels:
    app: divide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: divide
  template:
    metadata:
      labels:
        app: divide
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "divideapp"
        dapr.io/app-port: "4000"
        dapr.io/config: "appconfig"
        dapr.io/log-as-json: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"
        prometheus.io/scheme: "http"
    spec:
      containers:
      - name: divide
        image: dapriosamples/distributed-calculator-node:latest
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
